-- Zante 2027 database schema
-- Voting has been removed. Members can now be admins.

create table if not exists rooms (
  id bigint generated by default as identity primary key,
  name text not null,
  room_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists members (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  name text not null,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  unique(room_id, name)
);

alter table members add column if not exists is_admin boolean not null default false;

create table if not exists events (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  created_by bigint references members(id) on delete set null,
  title text not null,
  day integer not null check(day between 0 and 6),
  start_time time not null,
  end_time time not null,
  location text,
  description text,
  created_at timestamptz not null default now(),
  check(end_time > start_time)
);

create table if not exists ideas (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  created_by bigint references members(id) on delete set null,
  title text not null,
  description text,
  day integer not null check(day between 0 and 6),
  created_at timestamptz not null default now()
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  created_by bigint references members(id) on delete set null,
  title text not null,
  amount numeric(10,2) not null check(amount >= 0),
  created_at timestamptz not null default now()
);

create table if not exists packing_items (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  created_by bigint references members(id) on delete set null,
  text text not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

-- Remove the old voting system.
drop table if exists event_votes cascade;
drop table if exists votes cascade;

insert into rooms(name, room_key)
values ('Zante 2027', 'Zante2027!')
on conflict (room_key) do nothing;

-- Nate is the protected main admin.
update members
set is_admin = true
where lower(trim(name)) = 'nate';

create or replace function enforce_nate_admin()
returns trigger
language plpgsql
as $$
begin
  if lower(trim(new.name)) = 'nate' then
    new.is_admin := true;
  end if;
  return new;
end;
$$;

drop trigger if exists members_nate_admin on members;

create trigger members_nate_admin
before insert or update of name, is_admin
on members
for each row
execute function enforce_nate_admin();

alter table rooms enable row level security;
alter table members enable row level security;
alter table events enable row level security;
alter table ideas enable row level security;
alter table expenses enable row level security;
alter table packing_items enable row level security;

do $$ begin
  create policy rooms_read on rooms for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy members_all on members for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy events_all on events for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy ideas_all on ideas for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy expenses_all on expenses for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy packing_all on packing_items for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

grant select on rooms to anon, authenticated;
grant select, insert, update, delete on members, events, ideas, expenses, packing_items to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

do $$
declare t text;
begin
  foreach t in array array['members','events','ideas','expenses','packing_items']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table %I', t);
    end if;
  end loop;
end $$;