-- Zante 2027 database schema

create table if not exists rooms (
  id bigint generated by default as identity primary key,
  name text not null,
  room_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists members (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique(room_id, name)
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  created_by bigint references members(id) on delete set null,
  title text not null,
  day integer not null check(day between 0 and 6),
  start_time time not null,
  end_time time not null,
  location text,
  description text,
  created_at timestamptz not null default now(),
  check(end_time > start_time)
);

create table if not exists event_votes (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  member_id bigint not null references members(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(event_id, member_id)
);

create table if not exists ideas (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  created_by bigint references members(id) on delete set null,
  title text not null,
  description text,
  day integer not null check(day between 0 and 6),
  created_at timestamptz not null default now()
);

create table if not exists votes (
  id bigint generated by default as identity primary key,
  idea_id bigint not null references ideas(id) on delete cascade,
  member_id bigint not null references members(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(idea_id, member_id)
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  created_by bigint references members(id) on delete set null,
  title text not null,
  amount numeric(10,2) not null check(amount >= 0),
  created_at timestamptz not null default now()
);

create table if not exists packing_items (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  created_by bigint references members(id) on delete set null,
  text text not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

insert into rooms(name, room_key)
values ('Zante 2027', 'Zante2027!')
on conflict (room_key) do nothing;

alter table rooms enable row level security;
alter table members enable row level security;
alter table events enable row level security;
alter table event_votes enable row level security;
alter table ideas enable row level security;
alter table votes enable row level security;
alter table expenses enable row level security;
alter table packing_items enable row level security;

-- Simple policies suitable for this small private friends app.
-- For stronger security, move room-key verification behind an RPC or backend.

do $$ begin
  create policy rooms_read on rooms for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy members_all on members for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy events_all on events for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy event_votes_all on event_votes for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy ideas_all on ideas for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy votes_all on votes for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy expenses_all on expenses for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy packing_all on packing_items for all to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

grant select on rooms to anon, authenticated;
grant select, insert, update, delete on members, events, event_votes, ideas, votes, expenses, packing_items to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Realtime publication additions are guarded so the script can be rerun.
do $$
declare t text;
begin
  foreach t in array array['members','events','event_votes','ideas','votes','expenses','packing_items']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table %I', t);
    end if;
  end loop;
end $$;
